name: Survival-Horror-Build
on: [push] # The robot runs every time you hit "Commit"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Project Files
        uses: actions/checkout@v4
      
      - name: Prepare Java Engine
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile NodeJava Logic
        run: |
          # This compiles your health node and main logic
          javac NodeJava/NodeHP.java
          echo "NodeJava Compiled Successfully!"
          
